### PR TITLE
include hip_runtime.h fist

### LINKED ISSUE #515: Compile errors from hip/hip_fp16.h inclusion
A case discovered from HeCBench/logprob-hip. Reduced case:
```
$ cat include-hip-fp16.hip
#include <hip/hip_fp16.h>
#include <hip/hip_runtime.h>
$ ../install/bin/hipcc include-hip-fp16.hip -c
In file included from include-hip-fp16.hip:1:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/hip_fp16.h:41:
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_fp16.h:35:2: error: Include this file after including hip/hip_runtime.h
#error Include this file after including hip/hip_runtime.h
 ^
In file included from include-hip-fp16.hip:2:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/hip_runtime.h:73:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_runtime.h:46:
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_math_fwd.h:77:48: error: expected ')'
    __device__ __attribute__((const)) _Float16 __llvm_amdgcn_rcp_f16(_Float16);
                                               ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_fp16.h:30:45: note: expanded from macro '__llvm_amdgcn_rcp_f16'
#define __llvm_amdgcn_rcp_f16(__X) ((__half)1.0f / (__half)__X)
                                            ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_math_fwd.h:77:48: note: to match this '('
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_fp16.h:30:36: note: expanded from macro '__llvm_amdgcn_rcp_f16'
#define __llvm_amdgcn_rcp_f16(__X) ((__half)1.0f / (__half)__X)
                                   ^
In file included from include-hip-fp16.hip:2:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/hip_runtime.h:73:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_runtime.h:46:
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_math_fwd.h:233:12: error: expected ')'
    __2f16 __llvm_amdgcn_rcp_2f16(__2f16 x) // Not currently exposed by ROCDL.
           ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_fp16.h:31:47: note: expanded from macro '__llvm_amdgcn_rcp_2f16'
#define __llvm_amdgcn_rcp_2f16(__X) ((__half2)1.0f / (__half2)__X)
                                              ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_math_fwd.h:233:12: note: to match this '('
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_fp16.h:31:37: note: expanded from macro '__llvm_amdgcn_rcp_2f16'
#define __llvm_amdgcn_rcp_2f16(__X) ((__half2)1.0f / (__half2)__X)
                                    ^
In file included from include-hip-fp16.hip:2:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/hip_runtime.h:73:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_runtime.h:46:
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_math_fwd.h:235:9: error: expected expression
        return __2f16{__llvm_amdgcn_rcp_f16(x.x), __llvm_amdgcn_rcp_f16(x.y)};
        ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_math_fwd.h:236:6: error: expected ';' after top level declarator
    }
     ^
5 errors generated when compiling for .

failed to execute:/mnt/md1/linehill/ws-chip-spv-2/install/bin/clang++ -x hip include-hip-fp16.hip -D__HIP_PLATFORM_SPIRV__= --offload=spirv64 -Xclang -no-opaque-pointers -nohipwrapperinc --hip-path=/mnt/md1/linehill/ws-chip-spv-2/install --target=x86_64-unknown-linux-gnu -include /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_fixups.h -I//mnt/md1/linehill/ws-chip-spv-2/install/include   -c
```

### PR DESCRIPTION
**Pull request by pvelesko**
Fixes #515

### CODE REVIEW

File: include/hip/spirv_hip_fp16.h [hunk 1]
```diff
@@ -32,7 +32,7 @@ THE SOFTWARE.
 /* chipStar defines end */
 
 #ifndef HIP_INCLUDE_HIP_HIP_RUNTIME_H
-#error Include this file after including hip/hip_runtime.h
+#include <hip/hip_runtime.h>
 #endif
```
Comment (linehill) [inline include/hip/spirv_hip_fp16.h:36]: Please, remove the ifndef and endif lines too. They are redundant.

File: include/hip/spirv_hip_fp16.h [hunk 2]
```diff
@@ -1533,7 +1531,6 @@ THE SOFTWARE.
                     __llvm_amdgcn_rcp_f16(static_cast<__half_raw>(x).data)};
             }
 #endif
-            inline
```
Comment (linehill) [inline include/hip/spirv_hip_fp16.h:1536]: Accidental remove?

The `inline` keyword shouldn't be removed. As far as I can see, this would cause multiple definition errors.

Comment (linehill) [reply include/hip/spirv_hip_fp16.h:1536]: I see. To me the `if !defined(__HIP_PLATFORM_SPIRV__)` in the above is misplaced and it should encase the `inline` keyword that is just before it.

File: tests/compiler/TestHipccFp16Include.bash [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+set -eu
+
+SRC_DIR=@CMAKE_CURRENT_SOURCE_DIR@
+OUT_DIR=@CMAKE_CURRENT_BINARY_DIR@/@TEST_NAME@.d
+HIPCC=@CMAKE_BINARY_DIR@/bin/hipcc
+
+export HIPCC_VERBOSE=7
+mkdir -p ${OUT_DIR}
+
+${HIPCC} ${SRC_DIR}/inputs/testfp16include.cpp
```
Comment (linehill) [inline tests/compiler/TestHipccFp16Include.bash:12]: Do we have other test that also produces `a.out` in the same directory? If so, this test could clash with it when the tests are run parallel. Easily avoided by redirecting the output to /dev/null since this test is not interested in it.

File: tests/compiler/TestHipccFp16Include.bash [hunk 4]
```diff
@@ -0,0 +1,12 @@
+#!/bin/bash
+# Test the case where the hip/hip_fp16.h header is included before hip/hip_runtime.h 
+set -eu
+
+SRC_DIR=@CMAKE_CURRENT_SOURCE_DIR@
+OUT_DIR=@CMAKE_CURRENT_BINARY_DIR@/@TEST_NAME@.d
+HIPCC=@CMAKE_BINARY_DIR@/bin/hipcc
+
+export HIPCC_VERBOSE=7
+mkdir -p ${OUT_DIR}
```
Comment (linehill) [inline tests/compiler/TestHipccFp16Include.bash:10]: Seems unused - could be removed.

File: tests/compiler/TestHipccFp16Include.bash [hunk 5]
```diff
@@ -7,6 +7,5 @@ OUT_DIR=@CMAKE_CURRENT_BINARY_DIR@/@TEST_NAME@.d
 HIPCC=@CMAKE_BINARY_DIR@/bin/hipcc
 
 export HIPCC_VERBOSE=7
-mkdir -p ${OUT_DIR}
 
-${HIPCC} ${SRC_DIR}/inputs/testfp16include.cpp
+${HIPCC} ${SRC_DIR}/inputs/testfp16include.cpp > /dev/null
```
Comment (linehill) [inline tests/compiler/TestHipccFp16Include.bash:11]:
```suggestion
${HIPCC} ${SRC_DIR}/inputs/testfp16include.cpp -o /dev/null
```
Without the `-o` the compiler will write the output into `a.out`.

**Review by linehill — APPROVED** [review]
LGTM.

File: include/hip/spirv_hip_fp16.h [hunk 6]
```diff
@@ -1528,7 +1530,7 @@ THE SOFTWARE.
             __half hrcp(__half x)
             {
                 return __half_raw{
-                    __llvm_amdgcn_rcp_f16(static_cast<__half_raw>(x).data)};
+                    __llvm_rcp_f16(static_cast<__half_raw>(x).data)};
```
Comment (linehill) [inline include/hip/spirv_hip_fp16.h:1533]:
```
  This file is an almost verbatim copy of
  hipamd /include/hip/amd_detail/amd_hip_fp16.h (revision 348a177).

  Let's try to keep it as close to upstream and possible. No clang-format,
  and minimal modifications.
```
This change steers away from being close to upstream.

Comment (pvelesko) [reply include/hip/spirv_hip_fp16.h:1533]: > minimal modifications

What do you suggest and why do you think we should have any references to anything AMD-specific?

Comment (linehill) [reply include/hip/spirv_hip_fp16.h:1533]: Leave it and also the defines above as they were. The defines make sure AMD builtins does not end up into device binary.

Comment (pvelesko) [reply include/hip/spirv_hip_fp16.h:1533]: it fails to build. Again, why should we have `amdgcn` references in a file called `spirv_`? Does not make any sense to me.

Comment (linehill) [reply include/hip/spirv_hip_fp16.h:1533]: > it fails to build.

Could you elaborate how the build fails? 


> why should we have amdgcn references in a file called spirv_?

Minimal changes makes it easier to apply changes from the upstream (when/if we need) by having less merge conflicts to be dealt with.

Comment (pvelesko) [reply include/hip/spirv_hip_fp16.h:1533]: > Could you elaborate how the build fails?

references to amdgcn instrinsics. You can look at the logs yourself on github actions. 

> Minimal changes makes it easier to apply changes from the upstream (when/if we need) by having less merge conflicts to be dealt with.

these are minimal changes. 

Still haven't heard a good reason for having references to amdgcn in a spirv file.

Comment (linehill) [reply include/hip/spirv_hip_fp16.h:1533]: > references to amdgcn instrinsics. You can look at the logs yourself on github actions.

```
2023-08-23T14:47:21.6360757Z /home/pvelesko/actions-runner/_work/chipStar/chipStar/include/hip/spirv_math_fwd.h:77:48: error: expected ')'
2023-08-23T14:47:21.6361234Z     __device__ __attribute__((const)) _Float16 __llvm_amdgcn_rcp_f16(_Float16);
2023-08-23T14:47:21.6361597Z                                                ^
2023-08-23T14:47:21.6362326Z /home/pvelesko/actions-runner/_work/chipStar/chipStar/include/hip/spirv_hip_fp16.h:30:45: note: expanded from macro '__llvm_amdgcn_rcp_f16'
2023-08-23T14:47:21.6362719Z #define __llvm_amdgcn_rcp_f16(__X) ((__half)1.0f / (__half)__X)
...
```
The compiler error isn't about use of amdgcn intrinsic but a syntax error. And that happen because the `__llvm_amdgcn_rcp_f16` gets expanded by the macro from spirv_hip_fp16.h which is meant to replace calls and it breaks on function declarations. Header inclusion order change could explain why the error appears now.  The inclusion order is not the problem but the __llvm_amdgcn_rcp* defines in the beginning of spirv_hip_fp16.h header are not meant to be defined outside file. You can fix it by undefining them at the end of the spirv_hip_fp16.h:
```
#undef __llvm_amdgcn_rcp_f16
#undef __llvm_amdgcn_rcp_2f16
```

> Still haven't heard a good reason for having references to amdgcn in a spirv file.

I'm not in favor having amdgcn references in chipStar's HIP headers. The intent of having minimal changes on this file is to making applying changes from upstream with less trouble.

Comment (pvelesko) [reply include/hip/spirv_hip_fp16.h:1533]: > You can fix it by undefining them at the end of the spirv_hip_fp16.h:

or by removing all references to "amdgcn" - am I missing something here?

> I'm not in favor having amdgcn references in chipStar's HIP headers

I'd much rather not have any references to amdgcn than worry about changing a few lines next time we copy this file (not even clear if and when this would happen)

Since the beginning of this project, this header was copied once, maybe twice. I think so we're splitting hairs over what amounts to a couple of changed lines.

Comment (linehill) [reply include/hip/spirv_hip_fp16.h:1533]: Given the low amount of amdgcn references I'm in favor for removing them. CCing @pjaaskel to make sure he's fine with this too.

Comment (pjaaskel) [reply include/hip/spirv_hip_fp16.h:1533]: Sure!

**Review by pjaaskel — APPROVED** [review]
