### PR TITLE
Fix 513

### LINKED ISSUE #513: error: invalid operands to binary expression ('uchar2' ...
A case discovered from HeCBench/aes-hip. The following reduced reproducer:
```c++
#include <hip/hip_runtime.h>
__global__ void k(uchar2 x, uchar2 y) {
  auto t = x ^ y;
  printf("t=(%d, %d)\n", t.x, t.y);
}

int main() {
  k<<<1, 1>>>(make_uchar2(1, 2), make_uchar2(3, 3)); // Should print t=(2, 1)
  hipDeviceSynchronize();
  return 0;
}
``` 
Fails to compile:
```
$ ../install/bin/hipcc repro-uchar4.hip
repro-uchar4.hip:3:14: error: invalid operands to binary expression ('uchar2' (aka 'HIP_vector_type<unsigned char, 2>') and 'uchar2')
  auto t = x ^ y;
           ~ ^ ~
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_vector_types.h:364:30: note: candidate function not viable: call to __host__ function from __global__ function
inline HIP_vector_type<T, n> operator^(
                             ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_vector_types.h:370:30: note: candidate function not viable: call to __host__ function from __global__ function
inline HIP_vector_type<T, n> operator^(const HIP_vector_type<T, n>& x,
                             ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_vector_types.h:376:30: note: candidate function not viable: call to __host__ function from __global__ function
inline HIP_vector_type<T, n> operator^(
                             ^
1 error generated when compiling for .

failed to execute:/mnt/md1/linehill/ws-chip-spv-2/install/bin/clang++ -x hip repro-uchar4.hip -D__HIP_PLATFORM_SPIRV__= --offload=spirv64 -Xclang -no-opaque-pointers -nohipwrapperinc --hip-path=/mnt/md1/linehill/ws-chip-spv-2/install --target=x86_64-unknown-linux-gnu -include /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_fixups.h -L/mnt/md1/linehill/ws-chip-spv-2/install/lib -lCHIP -Wl,-rpath,/mnt/md1/linehill/ws-chip-spv-2/install/lib -I//mnt/md1/linehill/ws-chip-spv-2/install/include
```

### PR DESCRIPTION
**Pull request by pvelesko**
Fixes #513

### CODE REVIEW

File: include/hip/spirv_hip_complex.h [hunk 1]
```diff
@@ -106,15 +106,20 @@ THE SOFTWARE.
...
 #define COMPLEX_DIV_PREOP_OVERLOAD(type)                                                           \
-    __HOST_DEVICE__ static inline type& operator/=(type& lhs, const type& rhs) {               \
-        lhs = lhs / rhs;                                                                           \
+    __HOST_DEVICE__ static inline type& operator/=(type& lhs, const type& rhs) {                   \
+        type temp;                                                                                 \
+        temp.x = (lhs.x*rhs.x + lhs.y * rhs.y) / (rhs.x*rhs.x + rhs.y*rhs.y);                      \
+        temp.y = (lhs.y * rhs.x - lhs.x * rhs.y) / (rhs.x*rhs.x + rhs.y*rhs.y);                    \
+        lhs = temp;                                                                                \
         return lhs;                                                                                \
     }
```
Comment (pvelesko) [inline include/hip/spirv_hip_complex.h:124]: These changes are from hipamd - not sure if these were not present at the time of copy or if there was a reason for this change on our side.

**Comment by pvelesko** [comment]
The original issue is fixed by updating vector types but now hipComplex operators are ambigious:

```
/home/pvelesko/CHIP-SPV/hipccFixes9/include/hip/spirv_hip_complex.h:259:1: error: use of overloaded operator '/' is ambiguous (with operand types 'hipDoubleComplex' (aka 'HIP_vector_type<double, 2>') and 'const hipDoubleComplex' (aka 'const HIP_vector_type<double, 2>'))
COMPLEX_DIV_PREOP_OVERLOAD(hipDoubleComplex)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pvelesko/CHIP-SPV/hipccFixes9/include/hip/spirv_hip_complex.h:117:19: note: expanded from macro 'COMPLEX_DIV_PREOP_OVERLOAD'
        lhs = lhs / rhs;                                                                           \
              ~~~ ^ ~~~
/home/pvelesko/CHIP-SPV/hipccFixes9/include/hip/spirv_hip_vector_types.h:564:65: note: candidate function
        friend __HOST_DEVICE__ inline constexpr HIP_vector_type operator/(
                                                                ^
/home/pvelesko/CHIP-SPV/hipccFixes9/include/hip/spirv_hip_complex.h:255:1: note: candidate function
COMPLEX_DIV_OP_OVERLOAD(hipDoubleComplex)
^
/home/pvelesko/CHIP-SPV/hipccFixes9/include/hip/spirv_hip_complex.h:86:40: note: expanded from macro 'COMPLEX_DIV_OP_OVERLOAD'
    __HOST_DEVICE__ static inline type operator/(const type& lhs, const type& rhs) {           \
```

**Comment by pvelesko** [comment]
The issue arises from the fact that hipDoubleComplex is defined as a float2 vector so we end up with two function definitions for the same type (after hipDoubleComplex gets expanded to vector type) 

```
#define COMPLEX_MUL_OP_OVERLOAD(type) __HOST_DEVICE__ static inline type operator*(const type& lhs, const type& rhs) { type ret; ret.x = lhs.x * rhs.x - lhs.y * rhs.y; ret.y = lhs.x * rhs.y + lhs.y * rhs.x; return ret; }
Expands to:

 static inline hipDoubleComplex operator*(const hipDoubleComplex& lhs, const hipDoubleComplex& rhs) { hipDoubleComplex ret; ret.x = lhs.x * rhs.x - lhs.y * rhs.y; ret.y = lhs.x * rhs.y + lhs.y * rhs.x; return ret; }
```

Also not clear:
No `__host__ __device__` tag for these?
